name: "Bug Report"
description: "Create a report to help improve"
title: "[BUG] "
labels: ["bug"]
assignees:
  - Veicm
body:
  - type: markdown
    attributes:
      value: "## Bug Report\nPlease fill out the details below."

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Example: The application crashes when opening settings."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Example: The settings menu should open without crashing."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Drag and drop images here or provide a link."
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: "Select your OS."
      multiple: false
      options:
        - "Arch Linux"
        - "Ubuntu"
        - "Debian"
        - "Windows"
        - "Other (please specify below)"
    validations:
      required: true

  - type: input
    id: other_os
    attributes:
      label: "If Other, specify"
      description: "Enter your OS if it was not listed above."
      placeholder: "Example: RedHat"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false
